language: objective-c
osx_image: xcode10.2
cache:
    directories:
    - $HOME/.ccache
install:
- gem install xcpretty
- brew install ccache
- PATH=$PATH:/usr/local/opt/ccache/libexec
- brew install macmade/tap/xcode-coveralls
- export PYTHONUSERBASE=~/.local
- easy_install --user scan-build
script:
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Static Library" build test | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Static Library" analyze | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Dynamic Library" build test | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Dynamic Library" analyze | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Framework" build test | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ Mac Framework" analyze | xcpretty
- set -o pipefail && xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ iOS Static Library" -destination generic/platform=iOS build | xcpretty
- set -o pipefail && scan-build --status-bugs xcodebuild -project "CoreFoundation++.xcodeproj" -scheme "CF++ iOS Static Library" -destination generic/platform=iOS analyze | xcpretty
before_script:
- ccache -s
- ccache -z
after_script:
- ccache -s
after_success:
- bash Scripts/travis-after.sh
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
