name: CI
on: [push]
jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                run-config:
                    - { scheme: 'CF++ Mac Static Library',  project: 'CoreFoundation++.xcodeproj', actions: "build analyze test",  destination: 'platform=macOS' }
                    - { scheme: 'CF++ Mac Dynamic Library', project: 'CoreFoundation++.xcodeproj', actions: "build analyze test",  destination: 'platform=macOS' }
                    - { scheme: 'CF++ Mac Framework',       project: 'CoreFoundation++.xcodeproj', actions: "build analyze test",  destination: 'platform=macOS' }
                    - { scheme: 'CF++ iOS Static Library',  project: 'CoreFoundation++.xcodeproj', actions: "build analyze",       destination: 'platform=iOS Simulator,name=iPhone 12' }
        steps:
            
            - name: Checkout
              uses: actions/checkout@v1
              with:
                submodules: 'recursive'

            - name: Xcode - Version
              run: xcode-select -p

            - name: Xcode - SDKs
              run: xcodebuild -project '${{ matrix.run-config['project'] }}' -scheme '${{ matrix.run-config['scheme'] }}' -showsdks

            - name: Xcode - Destinations
              run: xcodebuild -project '${{ matrix.run-config['project'] }}' -scheme '${{ matrix.run-config['scheme'] }}' -showdestinations

            - name: Xcode - Build Settings
              run: xcodebuild -project '${{ matrix.run-config['project'] }}' -scheme '${{ matrix.run-config['scheme'] }}' -showBuildSettings

            - name: Xcode - Build
              run: xcodebuild -project '${{ matrix.run-config['project'] }}' -scheme '${{ matrix.run-config['scheme'] }}' -destination '${{ matrix.run-config['destination'] }}' -showBuildTimingSummary ${{ matrix.run-config['actions'] }} CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
